### ISSUE TITLE
Implement upgrade

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/shaarli_ynh#1]

**Comment by anmol26s** [comment]
Any update on it? I want to upgrade to latest version.

**Comment by lapineige** [comment]
I think @Rafi594 was working on it, but I had not enough time to take a look.

Meanwhile, you can export all your links, remove the app and install the new version, do the configuration, then import the links.

**Comment by anmol26s** [comment]
Thanks for the solution.

**Comment by lapineige** [comment]
Fixed by #26
