### ISSUE TITLE
Can't use shaarlier the android client

### ISSUE THREAD

**Issue by diaeresis** [YunoHost-Apps/shaarli_ynh#13]
If you wan't to add an account with the android shaarlier client. The application won't reconize the couple login / password of yunohost.

**Comment by lapineige** [comment]
Hi @diaeresis,
I'm planning to update to the new community fork, when it will be done (probably not a short term milestone), could you test it again, and open the issue again if it's not working ?
Thanks :)

**Comment by mro** [comment]
A user of my https://github.com/mro/ShaarliOS just has reported the same issue.

How's the situation with other clients like e.g. https://github.com/dimtion/Shaarlier/ ?
