### ISSUE TITLE
Hide useless menus for ynh

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/shaarli_ynh#2]
- user management menus are unused for ynh

**Comment by lapineige** [comment]
* So it should adapt to Yunohost's user creation/deletion ?
Even it does it correctly, I had issue with other apps and users management, so I'd prefer to keep it just in case (with a warning/tooltip to inform the user that it should know what he's doing before changing anything ?).

* Couldn't it be useful for a public version of the Shaarli ?

**Comment by rokaz** [comment]
I don't know how it was before, but it seems that the app has evoluted a lot in the community version and that they made the choice to have a single user app. So I believe this issue is not relevant anymore.

**Comment by lapineige** [comment]
But there is still an option to add administrator, moderator and so, right ?

**Comment by rokaz** [comment]
No, there is only one user. When logged you can add and edit the links, when not logged you can only see the public links.

**Comment by lapineige** [comment]
Ok, I made a confusion with the old one. 
So this issue is no longer relevant. Closing.
