### ISSUE TITLE
Can't import firefox bookmarks

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/shaarli_ynh#31]
The bookmarks.html file is 1047kb, but I still get nginx error:
413 Request Entity Too Large
Using 0.9.0 on Yunohost installation.

I have reported this (and [one minor](https://github.com/shaarli/Shaarli/issues/1118) issue) to Shaarli devs, but [looks like the problem is related to yunohost](https://github.com/shaarli/Shaarli/issues/1117).

**Comment by maitrey0da** [comment]
I notice this bug too

**Comment by lapineige** [comment]
Which version of the package do you use @cloo and @maitrey0da ? The latest one ? (It was updated 10 days ago)

**Comment by maitrey0da** [comment]
The version of Shaarli is v0.9.0.

I didn't find more information like a version of built. I don't know how to force an update.

Thanks.

**Comment by lapineige** [comment]
Please update to the latest version first.

As we have no upgrade script right now, you need to export your links (go in the "Tools" part, then "Export your data").
Then you can upgrade, from Yunohost admin UI (somewhere in Tools > Upgrade, if I remember well) or use `yunohost app upgrade shaarli`.
Then you can import your link from the backup.

And try again with Firefox bookmarks (I don't expect it to be working, but just in case).

**Comment by maitrey0da** [comment]
I tried : 
```
# yunohost app upgrade shaarli
Warning: Upgrading app shaarli...
Success! shaarli is already up to date
Error: No app to upgrade

```

**Comment by lapineige** [comment]
What's the output of `yunohost app info shaarli` ?

**Comment by maitrey0da** [comment]
Hum. 
```
# yunohost app info shaarli
description: The personal, minimalist, super-fast, no-database delicious clone
license: free
name: Shaarli
version: 0.8.3
```
The footer displays v0.9.0 ...

**Comment by lapineige** [comment]
Let's try `yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_ynh`

**Comment by maitrey0da** [comment]
Thanks.
The upgrade works, but the bug continue. I have a timeout with a tiny import file (755 Ko)

**Comment by lapineige** [comment]
> The upgrade works, but the bug continue. I have a timeout with a tiny import file (755 Ko)

As expected :) (enjoy the new version ;)

I just checked, I can import a 1Mo file on my Shaarli.

I'm wondering if it's not an issue with the php config... 

Let's try something: download this file https://pastebin.com/wC123YWh, name it bookmark.html.
Then try to import it.
What happens ?

**Comment by maitrey0da** [comment]
Hello,

Sorry for the delay. It's work with your file.
I also think this a php issue.

**Comment by lapineige** [comment]
Ok so the import is working, but there is an issue with larger files or with your file.

I'll try to get / create a larger file to test it.

**Comment by maitrey0da** [comment]
Hello,
Did you try to create larger file ? I can push my bookmark file if you want.

**Comment by anmol26s** [comment]
Is this issue still there?
