### ISSUE TITLE
Copy current themes on upgrade

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/shaarli_ynh#41]
Hi,

after upgrading the app on my yunohost instance Shaarli was broken: it failed to retrieve the template files declared in my config. My config states the "material" theme is the current theme (I downloaded it manually) but the upgrade erased my downloaded theme.

Maybe a backup of the themes (in `tpl`) should be done, like a backup of the config file is done: https://github.com/YunoHost-Apps/shaarli_ynh/blob/master/scripts/upgrade#L77
?

**Comment by lapineige** [comment]
Can you try to upgrade with this branch ?
`yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_ynh/tree/backup_theme`

**Comment by nicofrand** [comment]
Works like a charm!
