### ISSUE TITLE
Invalid app manifest: Expecting , 

### ISSUE THREAD

**Issue by Grimbox** [YunoHost-Apps/shaarli_ynh#43]
Hello :-)

I've just installed Yunohost on a freshly spawned server and I've encountered the following error when installing Shaarli through this repository:

```
admin@server:~$ sudo yunohost app install https://github.com/YunoHost-Apps/shaarli_ynh
WARNING! Installing 3rd party applications may compromise the integrity and security of your system. You should probably NOT install it unless you know what you are doing. Are you willing to take that risk? [Y/N] : y
Error: Invalid app manifest: Expecting , delimiter: line 55 column 9 (char 1523)
```

I suppose the problem lies within the `help` key in the [manifest.json file](https://github.com/YunoHost-Apps/shaarli_ynh/blob/master/manifest.json), with a missing `,`.

Thanks :-)

**Comment by lapineige** [comment]
Oh yeah, thanks… :sweat_smile:
Solved :)
