### ISSUE TITLE
Insufficient permissions:

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/shaarli_ynh#49]
i tried to install shaarli in new server yunohost... but: 
Insufficient permissions:
"data/log.txt" file is not writable

is it a bug ?

**Comment by alexAubin** [comment]
To be able to help you, please provide the full installation log as it should be advised in the error message ..

**Comment by thsfo** [comment]
Hello @alexAubin 

Tnaks you for you're help: https://paste.yunohost.org/raw/lanemudotu

**Comment by alexAubin** [comment]
Well this log shows that the installation worked, so what do you mean exactly by "I tried to install ... but"

Where does that message about insufficient permission comes from ?

**Comment by thsfo** [comment]
On continue en français camarade ?
Tu peux jeter un oeil ici : https://liens.orties.net/shaarli/

**Comment by GannonTdW** [comment]
salut
```bash
chmod 644 /var/www/shaarli/data/log.txt && chown shaarli: /var/www/shaarli/data/log.txt
```

C'est quand même mieux qu'un 777.

**Comment by arthurlutz** [comment]
getting same bug when installing shaarli on buster branch of yunohost

**Comment by lapineige** [comment]
It's still there ? This is supposed to be fixed, I think :thinking:

the log.txt file is present ?

**Comment by pipointzero** [comment]
Hi, yes it is still today ;)

**Comment by lapineige** [comment]
Is your yunohost instance up-to-date ?

**Comment by pipointzero** [comment]
I think so. I downloaded and installed like 2 weeks ago:
yunohost: 
  repo: now
  version: 3.6.5.3
yunohost-admin: 
  repo: now
  version: 3.6.5.1
moulinette: 
  repo: now
  version: 3.6.4.1
ssowat: 
  repo: now
  version: 3.6.4

**Comment by lapineige** [comment]
Ok, so the fix in Yunohost core should be there… I don't know what's going on :(

**Comment by TheNomad11** [comment]
same issue here with newest yunohost

**Comment by tituspijean** [comment]
The issue appears because the following command is done *after* setting the rights. So the file belongs to `root`:
https://github.com/YunoHost-Apps/shaarli_ynh/blob/250cdad37520796c4d8bfa9f5b7c24d2d162d88e/scripts/install#L156

**Comment by lapineige** [comment]
Oh, good point ! Thanks :)
