### ISSUE TITLE
Templates are not updated on upgrade (was: Title and descriptions fields do not autofill anymore)

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/shaarli_ynh#65]
### Describe the bug

When adding a link (ex: https://github.com/shaarli/Shaarli), the title and description fields are not auto-filled.

### Context

- This worked with the previous version of the package (0.10.4).
- I host it on a subdomain (b.domain.tld)
- Hardware: *Kimsufi 2G*
- YunoHost version: *4.0.8.3*
- I have access to my server: *Through SSH | through the webadmin*
- Using package version/branch: the latest available through the Yunohost update interface
- If upgrading, current package version: *0.12.1~ynh1*
- Theme: *default*

### Steps to reproduce

- Add a link, https://github.com/shaarli/Shaarli

### Expected behavior

- Field "Title" should be filled with "GitHub - shaarli/Shaarli: The personal, minimalist, super-fast, database free, bookmarking service - community repo"
- Description should be filled with "The personal, minimalist, super-fast, database free, bookmarking service - community repo - shaarli/Shaarli"

You can try on https://demo.shaarli.org/admin/shaare?post=https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli with login `demo` and password `demo`.

### Logs

I could not find any meaningful log.

**Comment by nicofrand** [comment]
The demo makes a request to `https://demo.shaarli.org/admin/metadata?url=https://github.com/shaarli/Shaarli` to retrieve the title and description.

**Comment by nicofrand** [comment]
On my install:

![image](https://user-images.githubusercontent.com/3419050/103206208-9d6ba200-48fb-11eb-95e1-2a725635db1c.png)

**Comment by nicofrand** [comment]
The demo loads a metadata.min.js script unlike my instance (and `tpl/default/editlink.html is not uptodate with  https://github.com/shaarli/Shaarli/blob/820cae27cfcc94af552818f3f1e5342e00478f6c/tpl/default/editlink.html#L104).

**Comment by nicofrand** [comment]
I think my `default` template was not updated along with the 0.12.1 version…

I just tried `yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_ynh/` and the template still seems obsolete. If I delete the directory and retry the upgrade the directory is not recreated.

https://github.com/YunoHost-Apps/shaarli_ynh/blob/master/scripts/upgrade#L77 should probably only copy templates that do not exist in the freshly downloaded source!

**Comment by lapineige** [comment]
Thanks for investigating into that issue !

**Comment by nicofrand** [comment]
The initial issue with templates was that everything currently installed was removed (templates downloaded by the user too) and only "official" templates (the ones in the sources) were available.

I do not believe we need to support manual changes to the templates: any modification in the source should be preferred or there will be bugs (like the current one).

To sum up: current templates directory should be copied only if not already existing in the sources.

**Comment by lapineige** [comment]
I believe #66 should fix this : it copies the files in shaarli folder, but don't override any existing file that was installed with the upgrade.

**Comment by lapineige** [comment]
:up:
