### ISSUE TITLE
Update to 0.12.1: templates were outdated - resulting in "You have been banned after too many failed login attempts" error

### ISSUE THREAD

**Issue by e-jim** [YunoHost-Apps/shaarli_ynh#67]
Hello,

A few days ago, I updated my Yunohost Shaarli through Yunohost. 
Since then, I couldn't connect to my Shaarli instance and got this error

![image](https://user-images.githubusercontent.com/5951377/104466889-fe5ecf80-55b5-11eb-87a1-cfa928ba76a0.png)

In the Nginx logs, I could see this error:  

> Undefined variable: user_can_login in /var/www/shaarli/tmp/loginform.b91ef64efc3688266305ea9b42e5017e.rtpl.php on line 10" while reading response header from upstream

I realised the issue was that the variable user_can_login was nowhere to be seen except in the templates. 
My templates were dating from 2019. 
So I downloaded the latest Shaarli version and copied its tpl folder to my /var/www/shaarli/tpl

I suppose the issue comes from this line in the upgrade procedure:

https://github.com/YunoHost-Apps/shaarli_ynh/blob/037f1541187039e82734b1c422a3ee5e56e4b117/scripts/upgrade#L86

I guess one should only copy back folder that are not vintage and default, which are shipped with shaarli itself.

**Comment by lapineige** [comment]
Thanks for investigating all that, this already solves everything… :+1:

That's a know problem, normally #66 should fix it. Can you try it ?
